name: Release

on:
  push:
    branches:
      - main

env:
  RELEASE_COMMIT_PATTERN: "^chore\\(release\\)"

jobs:
  check-commit:
    name: Check commit message
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check.outputs.should_release }}
    steps:
      - name: Check if commit matches release pattern
        id: check
        run: |
          if [[ "${GITHUB_EVENT_HEAD_COMMIT_MESSAGE}" =~ ${RELEASE_COMMIT_PATTERN} ]]; then
            echo "should_release=true" >> $GITHUB_OUTPUT
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_EVENT_HEAD_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

  release:
    name: Semantic Release
    needs: check-commit
    if: needs.check-commit.outputs.should_release == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  no-release:
    name: Skip release
    needs: check-commit
    if: needs.check-commit.outputs.should_release == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Skipping release
        run: echo "No release triggered — commit does not match '${RELEASE_COMMIT_PATTERN}'"
